# Generated by Django 5.0.6 on 2026-06-15 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('price_kes', models.IntegerField()),
                ('change_pct', models.FloatField()),
                ('is_up', models.BooleanField(default=True)),
                ('demand_level', models.CharField(default='High', max_length=20)),
                ('volume_tonnes', models.IntegerField(default=100)),
                ('recorded_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=150)),
                ('crop', models.CharField(max_length=100)),
                ('area_acres', models.FloatField()),
                ('soil_quality', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Prospering', 'Prospering'), ('Normal', 'Normal'), ('Needs Attention', 'Needs Attention')], default='Normal', max_length=20)),
                ('lat_center', models.FloatField()),
                ('lng_center', models.FloatField()),
                ('coordinates_json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PestAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('risk_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('sector', models.CharField(default='All Sectors', max_length=100)),
                ('description', models.TextField()),
                ('mitigation', models.TextField()),
                ('issued_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoilHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100)),
                ('moisture', models.IntegerField()),
                ('ph', models.FloatField()),
                ('nitrogen', models.IntegerField()),
                ('phosphorus', models.IntegerField()),
                ('potassium', models.IntegerField()),
                ('status', models.CharField(default='Optimal', max_length=50)),
                ('last_tested', models.DateTimeField(auto_now=True, null=True)),
                ('tips', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=20)),
                ('temp_high', models.IntegerField()),
                ('temp_low', models.IntegerField()),
                ('condition', models.CharField(max_length=50)),
                ('precip_chance', models.IntegerField()),
                ('wind_speed', models.IntegerField(default=12)),
                ('humidity', models.IntegerField(default=65)),
                ('pressure', models.IntegerField(default=1012)),
                ('visibility', models.IntegerField(default=10)),
                ('date', models.DateField()),
                ('is_today', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('read_by_farmer', models.BooleanField(default=False)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_consults', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
