# Generated by Django 5.0.6 on 2026-07-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_data', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Chat Message', 'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.AlterModelOptions(
            name='commodityprice',
            options={'ordering': ['crop'], 'verbose_name': 'Commodity Price', 'verbose_name_plural': 'Commodity Prices'},
        ),
        migrations.AlterModelOptions(
            name='consultmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Consultation Message', 'verbose_name_plural': 'Consultation Messages'},
        ),
        migrations.AlterModelOptions(
            name='farmregion',
            options={'ordering': ['name'], 'verbose_name': 'Farm Region', 'verbose_name_plural': 'Farm Regions'},
        ),
        migrations.AlterModelOptions(
            name='pestalert',
            options={'ordering': ['-issued_at'], 'verbose_name': 'Pest Alert', 'verbose_name_plural': 'Pest Alerts'},
        ),
        migrations.AlterModelOptions(
            name='soilhealth',
            options={'ordering': ['-last_tested'], 'verbose_name': 'Soil Health', 'verbose_name_plural': 'Soil Health Records'},
        ),
        migrations.AlterModelOptions(
            name='weatherrecord',
            options={'ordering': ['-date'], 'verbose_name': 'Weather Record', 'verbose_name_plural': 'Weather Records'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commodityprice',
            name='crop',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmregion',
            name='coordinates_json',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='farmregion',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmregion',
            name='status',
            field=models.CharField(choices=[('Prospering', 'Prospering'), ('Normal', 'Normal'), ('Needs Attention', 'Needs Attention')], db_index=True, default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='pestalert',
            name='risk_level',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pestalert',
            name='sector',
            field=models.CharField(db_index=True, default='All Sectors', max_length=100),
        ),
        migrations.AlterField(
            model_name='soilhealth',
            name='sector',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
