# Generated by Django 5.0.6 on 2026-06-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
