# Generated by Django 5.0.6 on 2026-07-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='supabase_uid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
